version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-g-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lrnszv2o125g"
s3_prefix = "aws-g-2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

